version: '3'

services:
  mariadb:
    image: 'bitnami/mariadb:10.6.12'
    container_name: 'mariadb'
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - './mariadb:/bitnami'
  phpmyadmin:
    image: 'bitnami/phpmyadmin:5.2.1'
    container_name: 'phpmyadmin'
    ports:
      - '8081:8080'

    